### ISSUE TITLE
websocket 怎么安装

### ISSUE THREAD

**Issue by kintzhao** [HorizonRDK/hobot_usb_cam#4]
ros2 launch websocket websocket.launch.py websocket_image_topic:=/image websocket_only_show_image:=true
file 'websocket.launch.py' was not found in the share directory of package 'websocket' which is at '/opt/tros/share/websocket'

**Comment by zhukao** [comment]
tros版本号是多少，推荐升级到最新版本，手册对应于最新发布版本功能。
版本发布情况参考手册：https://developer.horizon.cc/documents_tros/quick_start/changelog
开发者社区论坛上提问响应速度会更快：https://developer.horizon.ai/forum

**Comment by qwdasfasfd** [comment]
![捕获](https://github.com/HorizonRDK/hobot_usb_cam/assets/96693293/0f6e5a63-c508-465f-b867-e92459524936)
web端无法显示图片，开发板ip为默认ip

**Comment by zhukao** [comment]
> ![捕获](https://private-user-images.githubusercontent.com/96693293/312316582-0f6e5a63-c508-465f-b867-e92459524936.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjEzODMsIm5iZiI6MTcxMDMyMTA4MywicGF0aCI6Ii85NjY5MzI5My8zMTIzMTY1ODItMGY2ZTVhNjMtYzUwOC00NjVmLWI4NjctZTkyNDU5NTI0OTM2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZDU1NjE2ZTExMWNiZTY0NjgxM2U4NWVkYjExZGVhMTY1YmI0OWViZDQ2ZDQyOTVkMmZiODc2Nzg2OWYwZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1cjI8NMPSF7UBUgAiHVpTh5zYEkYT2-dq5-k5DsPNd4) web端无法显示图片，开发板ip为默认ip

web端输入的url不对，如果是默认IP，应该输入http://192.168.1.10:8000。
具体说明参考：https://developer.horizon.cc/documents_tros/quick_demo/demo_render#web%E5%B1%95%E7%A4%BA
