### ISSUE TITLE
发布mjpeg时使用sensor_msgs/msg/CompressedImage

### ISSUE THREAD

**Issue by Hibanaw** [HorizonRDK/hobot_usb_cam#7]
2.1.1版本
当`pixel_format`被设置为`mjpeg`时，发布的消息类型为`sensor_msgs/msg/Image`
为何不使用`sensor_msgs/msg/CompressedImage`而使用`sensor_msgs/msg/Image`？

**Comment by zhukao** [comment]
这是一个历史遗留问题 :( ，切换消息类型的影响面太大，所以一直没有切换。
不过在2.1.3版本上修复了这个问题，这个版本目前还在内部测试中。https://github.com/HorizonRDK/robot_dev_config/blob/develop/CHANGELOG.md#v213-2024-03-11
