### ISSUE TITLE
/hbmem_image 消息类型错误 

### ISSUE THREAD

**Issue by xiaocaof** [HorizonRDK/hobot_usb_cam#9]
我得到的/hbmen_image 的消息类型为rcl_interfaces/msg/HobotMemoryCommon 而不是 /hbm_img_msgs/msg/HbmMsg1080P 为什么

**Comment by xiaocaof** [comment]
![Uploading {8FD8F690-DA69-4acb-B96F-2E1B5FF98427}.png…]()

**Comment by zhukao** [comment]
这是因为在`zero-copy`通信方式下，实际传输的是用于标识共享内存状态的`rcl_interfaces/msg/HobotMemoryCommon`类型消息，在`rclcpp`层再将共享内存地址`static_cast`到实际的消息类型`hbm_img_msgs/msg/HbmMsg1080P`。
即`hbm_img_msgs/msg/HbmMsg1080P`只是定义了**内存地址的解析方法**，所以使用命令查topic对应的**实际传输的消息类型**是`rcl_interfaces/msg/HobotMemoryCommon`。
